SUMMARY = "Fork of the popular zip manipulation library found in the zlib distribution"
DESCRIPTION = "minizip-ng is a zip manipulation library written in C that is supported on Windows, macOS, and Linux."
AUTHOR = "Nathan Moinvaziri <nathan@nathanm.com>"
HOMEPAGE = "https://www.github.com/zlib-ng/minizip-ng"
BUGTRACKER = "https://www.github.com/zlib-ng/minizip-ng/issues"
SECTION = "tools"
LICENSE = "Zlib"

CVE_PRODUCT = ""

