SUMMARY = "Library for nonlinear optimization"
DESCRIPTION = "NLopt is a library for nonlinear local and global optimization, for functions with and without gradient information. It is designed as a simple, unified interface and packaging of several free/open-source nonlinear optimization libraries."
AUTHOR = "Steven G. Johnson <stevenj@alum.mit.edu>"
HOMEPAGE = "https://github.com/stevengj/nlopt"
BUGTRACKER = "https://github.com/stevengj/nlopt/issues"
SECTION = "development"
LICENSE = "LGPL-2.0-or-later"

CVE_PRODUCT = ""
