SUMMARY = "RPyC (Remote Python Call) - A transparent and symmetric RPC library for python"
DESCRIPTION = "RPyC is a transparent python library for symmetrical remote procedure calls, clustering and distributed-computing."
AUTHOR = "tomerfiliba-org"
HOMEPAGE = "https://rpyc.readthedocs.io"
BUGTRACKER = "https://github.com/tomerfiliba-org/rpyc/issues"
SECTION = "development"
LICENSE = "MIT"

CVE_PRODUCT = ""

