SUMMARY = "JavaScript to Python Translator and JavaScript interpreter."
DESCRIPTION = "Translates JavaScript to Python code. Js2Py is able to translate and execute virtually any JavaScript code. Js2Py is written in pure python and does not have any dependencies. Basically an implementation of JavaScript core in pure python."
AUTHOR = "Piotr Dabkowski <piodrus@gmail.com>"
HOMEPAGE = "https://github.com/PiotrDabkowski/Js2Py"
BUGTRACKER = "https://github.com/PiotrDabkowski/Js2Py/issues"
SECTION = "development"
LICENSE = "MIT"

CVE_PRODUCT = ""

