SUMMARY = "cmocka is an elegant unit testing framework for C with support for mock objects."
DESCRIPTION = "cmocka is an elegant unit testing framework for C with support for mock objects. It only requires the standard C library, works on a range of computing platforms (including embedded) and with different compilers."
AUTHOR = "Andreas Schneider <asn@cryptomilk.org>, Jakub Hrozek <jakub.hrozek@posteo.se>"
HOMEPAGE = "https://cmocka.org/"
BUGTRACKER = "https://gitlab.com/cmocka/cmocka/-/issues"
SECTION = "development"
LICENSE = "Apache-2"

CVE_PRODUCT = ""
