SUMMARY = "Extra modules and scripts for CMake"
DESCRIPTION = "The Extra CMake Modules package adds to the modules and provides common build settings used in software produced by the KDE community."
AUTHOR = "KDE.org"
HOMEPAGE = "https://invent.kde.org/frameworks/extra-cmake-modules"
BUGTRACKER = "https://invent.kde.org/frameworks/extra-cmake-modules/-/issues"
SECTION = "console/utils"
LICENSE = "BSD"

CVE_PRODUCT = ""
