SUMMARY = "Static analysis of C/C++ code"
DESCRIPTION = "Cppcheck is a static analysis tool for C/C++ code. It provides unique code analysis to detect bugs and focuses on detecting undefined behaviour and dangerous coding constructs."
AUTHOR = "Daniel Marjamäki <daniel.marjamaki@gmail.com>"
HOMEPAGE = "http://cppcheck.sourceforge.net/"
BUGTRACKER = "https://trac.cppcheck.net/"
SECTION = "development"
LICENSE = "GPL-3.0-or-later"

CVE_PRODUCT = ""
