SUMMARY = "A modern, C++-native, test framework for unit-tests, TDD and BDD"
DESCRIPTION = "Catch2 is mainly a unit testing framework for C++, but it also provides basic micro-benchmarking features, and simple BDD macros."
AUTHOR = "Catch"
HOMEPAGE = "https://github.com/catchorg/Catch2"
BUGTRACKER = "https://github.com/catchorg/Catch2/issues"
SECTION = "development"
LICENSE = "BSL-1.0"

CVE_PRODUCT = ""

