SUMMARY = "Fast JavaScript parser for Python."
DESCRIPTION = "Fast JavaScript parser - manual translation of esprima.js to python. Takes 1 second to parse whole angular.js library so parsing speed is about 100k characters per second which makes it the fastest and most comprehensible JavaScript parser for python out there."
AUTHOR = "Piotr Dabkowski <piodrus@gmail.com>"
HOMEPAGE = "https://github.com/PiotrDabkowski/pyjsparser"
BUGTRACKER = "https://github.com/PiotrDabkowski/pyjsparser/issues"
SECTION = "development"
LICENSE = "MIT"

CVE_PRODUCT = ""
