SUMMARY = "CppUTest unit testing and mocking framework for C/C++"
DESCRIPTION = "CppUTest is a C /C++ based unit xUnit test framework for unit testing and for test-driving your code. It is written in C++ but is used in C and C++ projects and frequently used in embedded systems but it works for any C/C++ project."
AUTHOR = "CppUTest"
HOMEPAGE = "https://github.com/cpputest/cpputest"
BUGTRACKER = "https://github.com/cpputest/cpputest/issues"
SECTION = "development"
LICENSE = "BSD-3-Clause"

CVE_PRODUCT = ""
