SUMMARY = "Command line interface to the X11 clipboard"
DESCRIPTION = "xclip is a command line utility that is designed to run on any system with an X11 implementation. It provides an interface to X selections ("the clipboard") from the command line. It can read data from standard in or a file and place it in an X selection for pasting into other X applications. xclip can also print an X selection to standard out, which can then be redirected to a file or another program."
AUTHOR = "Peter Åstrand <astrand@lysator.liu.se>"
HOMEPAGE = "https://github.com/astrand/xclip"
BUGTRACKER = "https://github.com/astrand/xclip/issues"
SECTION = "tools"
LICENSE = "GPL-2.0-or-later"

CVE_PRODUCT = ""
