SUMMARY = "Library for communicating with spacenavd or 3dxsrv"
DESCRIPTION = "Libspnav is a C library for receiving input from 6 degrees-of-freedom (6dof) input devices, also known as spacemice, spaceballs, etc.."
AUTHOR = "Spacenav Project <spacenav-users@lists.sourceforge.net>"
HOMEPAGE = "https://github.com/FreeSpacenav/libspnav"
BUGTRACKER = "https://github.com/FreeSpacenav/libspnav/issues"
SECTION = "development"
LICENSE = "BSD-3-Clause"

CVE_PRODUCT = ""
