SUMMARY = "Library to read and write Data Matrix barcodes"
DESCRIPTION = "A software library that enables programs to read and write Data Matrix barcodes of the modern ECC200 variety."
AUTHOR = "Vadim A. Misbakh-Soloviov <dmtx@mva.name>"
HOMEPAGE = "https://github.com/dmtx/libdmtx"
BUGTRACKER = "https://github.com/dmtx/libdmtx/issues"
SECTION = "development"
LICENSE = "BSD-2-Clause"

CVE_PRODUCT = ""
