SUMMARY = "Command line interface to the freedesktop.org trashcan."
DESCRIPTION = "trash-cli trashes files recording the original path, deletion date, and permissions. It uses the same trashcan used by KDE, GNOME, and XFCE, but you can invoke it from the command line (and scripts)."
AUTHOR = "Andrea Francia"
HOMEPAGE = "https://github.com/andreafrancia/trash-cli"
BUGTRACKER = "https://github.com/andreafrancia/trash-cli/issues"
SECTION = "tools"
LICENSE = "GPL-2.0-only"

CVE_PRODUCT = ""
