SUMMARY = "GammaRay Qt introspection probe"
DESCRIPTION = "GammaRay is a software introspection tool for Qt applications developed by KDAB"
AUTHOR = "Klarälvdalens Datakonsult AB (KDAB)"
HOMEPAGE = "http://www.kdab.com/gammaray"
BUGTRACKER = "https://github.com/KDAB/GammaRay/issues"
SECTION = "tools"
LICENSE = "GPLv2"

CVE_PRODUCT = ""

BRANCH = "master"
PV = "2.11.3.99+git${SRCPV}"
SRCREV = "40e19a4ced8172f7bb8612f61b7276b87be15ffc"
